#!/usr/bin/env node

/**
 * KNOWLEDGE BASE NURTURING SCRIPT
 *
 * Creates a NEW enriched database from the original OSM data.
 * Scrapes Google for each place and saves IMMEDIATELY after each one.
 * Original database is NEVER modified.
 *
 * Features:
 * - Keeps original database safe
 * - Saves after EVERY place (no data loss)
 * - Can resume from where it left off
 * - Creates production-ready enriched database
 *
 * Usage:
 *   npm run nurture:kb              # Start fresh
 *   npm run nurture:kb:resume       # Resume from last place
 *   npm run nurture:kb:test         # Test on 5 places
 */

import puppeteer, { Browser, Page } from 'puppeteer';
import * as fs from 'fs';
import * as path from 'path';

// ============ CONFIGURATION ============

const CONFIG = {
  // Timing
  MIN_DELAY: 3500,
  MAX_DELAY: 6000,
  PAGE_LOAD_TIMEOUT: 30000,

  // Paths - ORIGINAL is never modified
  ORIGINAL_DB: path.join(process.cwd(), 'data', 'osm-scraped', 'osm-knowledge.json'),

  // NEW enriched database (this is what we build)
  ENRICHED_DIR: path.join(process.cwd(), 'data', 'enriched-knowledge'),
  ENRICHED_JSON: path.join(process.cwd(), 'data', 'enriched-knowledge', 'knowledge-base.json'),
  ENRICHED_TS: path.join(process.cwd(), 'data', 'enriched-knowledge', 'knowledge-base.ts'),
  PROGRESS_FILE: path.join(process.cwd(), 'data', 'enriched-knowledge', 'progress.json'),

  // Scraping
  MAX_PHOTOS: 5,
  USER_AGENT: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
};

// ============ TYPES ============

interface KnowledgeNode {
  id: string;
  name: string;
  category: string;
  subcategory?: string;
  description: string;
  shortDescription?: string;
  tags: string[];
  location: {
    island: string;
    area?: string;
    district?: string;
    address?: string;
    coordinates?: { lat: number; lng: number };
    latitude?: number;
    longitude?: number;
  };
  ratings: {
    overall: number;
    reviewCount: number;
    breakdown?: Record<string, number>;
  };
  media: {
    thumbnail: string;
    images: string[];
    virtualTour?: string;
  };
  contact: {
    phone?: string;
    email?: string;
    website?: string;
    bookingUrl?: string;
    social?: Record<string, string>;
  };
  hours?: {
    display?: string;
    schedule?: Record<string, string>;
    timezone?: string;
  };
  business: {
    priceRange?: string;
    currency?: string;
    established?: number;
    capacity?: number;
  };
  highlights?: string[];
  amenities?: string[];
  // New fields for enrichment tracking
  enrichment?: {
    source: 'google' | 'original';
    enrichedAt?: string;
    hasRealRating: boolean;
    hasRealPhotos: boolean;
    hasRealContact: boolean;
  };
}

interface Progress {
  totalPlaces: number;
  processedCount: number;
  lastProcessedId: string | null;
  processedIds: string[];
  failedIds: string[];
  startedAt: string;
  lastUpdated: string;
  stats: {
    ratingsEnriched: number;
    photosEnriched: number;
    contactEnriched: number;
    hoursEnriched: number;
  };
}

// ============ UTILITIES ============

function sleep(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms));
}

function randomDelay(): number {
  return CONFIG.MIN_DELAY + Math.random() * (CONFIG.MAX_DELAY - CONFIG.MIN_DELAY);
}

function sanitizeForSearch(name: string): string {
  return name
    .replace(/[&]/g, 'and')
    .replace(/['"]/g, '')
    .replace(/[^\w\s-]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function ensureDir(dirPath: string): void {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }
}

// ============ DATABASE MANAGEMENT ============

function loadOriginalDatabase(): KnowledgeNode[] {
  if (!fs.existsSync(CONFIG.ORIGINAL_DB)) {
    throw new Error(`Original database not found: ${CONFIG.ORIGINAL_DB}`);
  }
  return JSON.parse(fs.readFileSync(CONFIG.ORIGINAL_DB, 'utf-8'));
}

function loadEnrichedDatabase(): KnowledgeNode[] {
  if (fs.existsSync(CONFIG.ENRICHED_JSON)) {
    return JSON.parse(fs.readFileSync(CONFIG.ENRICHED_JSON, 'utf-8'));
  }
  return [];
}

function saveEnrichedDatabase(nodes: KnowledgeNode[]): void {
  ensureDir(CONFIG.ENRICHED_DIR);

  // Save JSON
  fs.writeFileSync(CONFIG.ENRICHED_JSON, JSON.stringify(nodes, null, 2));

  // Save TypeScript module
  const tsContent = `/**
 * ENRICHED KNOWLEDGE BASE
 * Auto-generated by nurture-knowledge-base.ts
 * Generated: ${new Date().toISOString()}
 *
 * Total places: ${nodes.length}
 * With real ratings: ${nodes.filter(n => n.enrichment?.hasRealRating).length}
 * With real photos: ${nodes.filter(n => n.enrichment?.hasRealPhotos).length}
 * With real contact: ${nodes.filter(n => n.enrichment?.hasRealContact).length}
 */

import type { KnowledgeNode } from '../../types/chatbot';

export const ENRICHED_KNOWLEDGE: KnowledgeNode[] = ${JSON.stringify(nodes, null, 2)};

export default ENRICHED_KNOWLEDGE;
`;

  fs.writeFileSync(CONFIG.ENRICHED_TS, tsContent);
}

function loadProgress(): Progress {
  if (fs.existsSync(CONFIG.PROGRESS_FILE)) {
    return JSON.parse(fs.readFileSync(CONFIG.PROGRESS_FILE, 'utf-8'));
  }
  return {
    totalPlaces: 0,
    processedCount: 0,
    lastProcessedId: null,
    processedIds: [],
    failedIds: [],
    startedAt: new Date().toISOString(),
    lastUpdated: new Date().toISOString(),
    stats: {
      ratingsEnriched: 0,
      photosEnriched: 0,
      contactEnriched: 0,
      hoursEnriched: 0
    }
  };
}

function saveProgress(progress: Progress): void {
  ensureDir(CONFIG.ENRICHED_DIR);
  progress.lastUpdated = new Date().toISOString();
  fs.writeFileSync(CONFIG.PROGRESS_FILE, JSON.stringify(progress, null, 2));
}

// ============ GOOGLE SCRAPER ============

class GoogleScraper {
  private browser: Browser | null = null;
  private page: Page | null = null;

  async initialize(): Promise<void> {
    console.log('🚀 Launching browser...');

    this.browser = await puppeteer.launch({
      headless: true,
      args: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage',
        '--disable-accelerated-2d-canvas',
        '--disable-gpu',
        '--window-size=1920,1080'
      ]
    });

    this.page = await this.browser.newPage();
    await this.page.setUserAgent(CONFIG.USER_AGENT);
    await this.page.setViewport({ width: 1920, height: 1080 });

    // Block unnecessary resources
    await this.page.setRequestInterception(true);
    this.page.on('request', (req) => {
      if (['font', 'stylesheet'].includes(req.resourceType())) {
        req.abort();
      } else {
        req.continue();
      }
    });

    console.log('✅ Browser ready\n');
  }

  async close(): Promise<void> {
    if (this.browser) {
      await this.browser.close();
    }
  }

  async scrapePlace(place: KnowledgeNode): Promise<{
    rating?: number;
    reviewCount?: number;
    photos: string[];
    phone?: string;
    website?: string;
    address?: string;
    hours?: string;
    priceLevel?: string;
  } | null> {
    if (!this.page) throw new Error('Browser not initialized');

    const searchQuery = `${sanitizeForSearch(place.name)} ${place.location.area || ''} Cayman Islands`;

    try {
      // Try Google Maps for best data
      const mapsUrl = `https://www.google.com/maps/search/${encodeURIComponent(searchQuery)}`;

      await this.page.goto(mapsUrl, {
        waitUntil: 'networkidle2',
        timeout: CONFIG.PAGE_LOAD_TIMEOUT
      });

      await sleep(2500);

      // Click first result if there's a list
      const firstResult = await this.page.$('[role="feed"] > div:first-child');
      if (firstResult) {
        await firstResult.click();
        await sleep(2000);
      }

      const data = await this.page.evaluate((maxPhotos: number) => {
        const result: {
          rating?: number;
          reviewCount?: number;
          photos: string[];
          phone?: string;
          website?: string;
          address?: string;
          hours?: string;
          priceLevel?: string;
        } = { photos: [] };

        // RATING - Multiple selectors
        const ratingSelectors = [
          'div.fontDisplayLarge',
          'span.ceNzKf',
          'span[aria-hidden="true"]'
        ];

        for (const selector of ratingSelectors) {
          const el = document.querySelector(selector);
          if (el) {
            const text = el.textContent || '';
            const match = text.match(/^(\d+[.,]\d+)$/);
            if (match) {
              result.rating = parseFloat(match[1].replace(',', '.'));
              break;
            }
          }
        }

        // Try aria-label on star icons
        if (!result.rating) {
          const starEl = document.querySelector('[role="img"][aria-label*="star"]');
          if (starEl) {
            const label = starEl.getAttribute('aria-label') || '';
            const match = label.match(/(\d+[.,]?\d*)\s*star/i);
            if (match) {
              result.rating = parseFloat(match[1].replace(',', '.'));
            }
          }
        }

        // REVIEW COUNT
        const reviewSelectors = [
          'button[aria-label*="review"]',
          'button[aria-label*="avis"]',
          '.F7nice span[aria-label]'
        ];

        for (const selector of reviewSelectors) {
          const el = document.querySelector(selector);
          if (el) {
            const text = (el.getAttribute('aria-label') || el.textContent || '').replace(/[,.\s]/g, '');
            const match = text.match(/(\d+)\s*(review|avis|comment)/i);
            if (match) {
              result.reviewCount = parseInt(match[1]);
              break;
            }
          }
        }

        // ADDRESS
        const addressEl = document.querySelector('[data-item-id="address"]') ||
                         document.querySelector('button[data-tooltip="Copy address"]') ||
                         document.querySelector('[aria-label*="Address"]');
        if (addressEl) {
          result.address = addressEl.textContent?.trim();
        }

        // PHONE
        const phoneEl = document.querySelector('[data-item-id^="phone"]') ||
                       document.querySelector('button[data-tooltip="Copy phone number"]') ||
                       document.querySelector('a[href^="tel:"]');
        if (phoneEl) {
          result.phone = phoneEl.textContent?.trim() || phoneEl.getAttribute('href')?.replace('tel:', '');
        }

        // WEBSITE
        const websiteEl = document.querySelector('[data-item-id="authority"]') ||
                         document.querySelector('a[data-tooltip="Open website"]') ||
                         document.querySelector('a[aria-label*="website"]');
        if (websiteEl) {
          result.website = websiteEl.getAttribute('href') || undefined;
        }

        // HOURS
        const hoursEl = document.querySelector('[aria-label*="hour"]') ||
                       document.querySelector('[aria-label*="heure"]');
        if (hoursEl) {
          result.hours = hoursEl.getAttribute('aria-label')?.replace(/^Hours?:\s*/i, '');
        }

        // PRICE LEVEL
        const priceEl = document.querySelector('[aria-label*="Price"]');
        if (priceEl) {
          const text = priceEl.getAttribute('aria-label') || priceEl.textContent || '';
          const match = text.match(/(\$+)/);
          if (match) result.priceLevel = match[1];
        }

        // PHOTOS - Get high quality images
        const photoEls = document.querySelectorAll('img[src*="googleusercontent"]');
        photoEls.forEach((img) => {
          const src = img.getAttribute('src');
          if (src && src.startsWith('http') && result.photos.length < maxPhotos) {
            // Skip tiny profile photos
            if (!src.includes('w36-h36') && !src.includes('s36-c') && !src.includes('w24-h24')) {
              result.photos.push(src);
            }
          }
        });

        return result;
      }, CONFIG.MAX_PHOTOS);

      return data;

    } catch (error) {
      console.error(`   ❌ Scrape error: ${error}`);
      return null;
    }
  }
}

// ============ ENRICHMENT LOGIC ============

function enrichPlace(original: KnowledgeNode, googleData: {
  rating?: number;
  reviewCount?: number;
  photos: string[];
  phone?: string;
  website?: string;
  address?: string;
  hours?: string;
  priceLevel?: string;
} | null): { enriched: KnowledgeNode; changes: string[] } {

  const enriched: KnowledgeNode = JSON.parse(JSON.stringify(original)); // Deep clone
  const changes: string[] = [];

  // Track what was enriched
  let hasRealRating = false;
  let hasRealPhotos = false;
  let hasRealContact = false;

  if (!googleData) {
    // No Google data, keep original but mark as not enriched
    enriched.enrichment = {
      source: 'original',
      hasRealRating: false,
      hasRealPhotos: false,
      hasRealContact: false
    };
    return { enriched, changes: ['No Google data found'] };
  }

  // RATING - Only update if Google has real data and original was default (4.0)
  if (googleData.rating && googleData.rating > 0) {
    const wasDefault = original.ratings.overall === 4.0 || original.ratings.overall === 4;
    if (wasDefault || googleData.rating !== original.ratings.overall) {
      enriched.ratings = {
        overall: googleData.rating,
        reviewCount: googleData.reviewCount || original.ratings.reviewCount
      };
      changes.push(`Rating: ${original.ratings.overall} → ${googleData.rating}`);
      hasRealRating = true;
    }
  }

  // PHOTOS - Replace if Google has better photos
  if (googleData.photos && googleData.photos.length > 0) {
    const hadPlaceholder = !original.media?.thumbnail ||
                          original.media.thumbnail.includes('placeholder') ||
                          original.media.thumbnail.includes('unsplash') ||
                          original.media.thumbnail.includes('via.placeholder');

    if (hadPlaceholder || googleData.photos.length > (original.media?.images?.length || 0)) {
      enriched.media = {
        ...enriched.media,
        thumbnail: googleData.photos[0],
        images: googleData.photos
      };
      changes.push(`Photos: ${original.media?.images?.length || 0} → ${googleData.photos.length}`);
      hasRealPhotos = true;
    }
  }

  // CONTACT INFO
  if (googleData.phone || googleData.website) {
    const hadNoContact = !original.contact?.phone && !original.contact?.website;

    enriched.contact = {
      ...enriched.contact,
      phone: googleData.phone || enriched.contact?.phone,
      website: googleData.website || enriched.contact?.website
    };

    if (googleData.phone && !original.contact?.phone) {
      changes.push(`Phone: added`);
      hasRealContact = true;
    }
    if (googleData.website && !original.contact?.website) {
      changes.push(`Website: added`);
      hasRealContact = true;
    }
  }

  // ADDRESS
  if (googleData.address && (!original.location.address || googleData.address.length > original.location.address.length)) {
    enriched.location = {
      ...enriched.location,
      address: googleData.address
    };
    changes.push(`Address: updated`);
  }

  // HOURS
  if (googleData.hours && !original.hours?.display) {
    enriched.hours = {
      ...enriched.hours,
      display: googleData.hours
    };
    changes.push(`Hours: added`);
  }

  // PRICE LEVEL
  if (googleData.priceLevel && !original.business?.priceRange) {
    enriched.business = {
      ...enriched.business,
      priceRange: googleData.priceLevel
    };
    changes.push(`Price: ${googleData.priceLevel}`);
  }

  // Mark enrichment status
  enriched.enrichment = {
    source: 'google',
    enrichedAt: new Date().toISOString(),
    hasRealRating,
    hasRealPhotos,
    hasRealContact
  };

  return { enriched, changes };
}

// ============ MAIN PROCESS ============

async function main() {
  const args = process.argv.slice(2);
  const isResume = args.includes('--resume');
  const isTest = args.includes('--test');
  const limitArg = args.find(a => a.startsWith('--limit='));
  const limit = limitArg ? parseInt(limitArg.split('=')[1]) : (isTest ? 5 : undefined);

  console.log('═'.repeat(70));
  console.log('        KNOWLEDGE BASE NURTURING - Real Data Enrichment');
  console.log('═'.repeat(70));
  console.log(`\n📋 Mode: ${isResume ? 'RESUME' : 'FRESH START'}${isTest ? ' (TEST)' : ''}`);
  if (limit) console.log(`📊 Limit: ${limit} places`);

  // Ensure output directory exists
  ensureDir(CONFIG.ENRICHED_DIR);

  // Load original database (never modified)
  const originalDB = loadOriginalDatabase();
  console.log(`\n📚 Original database: ${originalDB.length} places (SAFE - won't be modified)`);

  // Load or initialize enriched database
  let enrichedDB: KnowledgeNode[] = [];
  let progress: Progress;

  if (isResume) {
    enrichedDB = loadEnrichedDatabase();
    progress = loadProgress();
    console.log(`📈 Resuming: ${progress.processedCount}/${originalDB.length} already processed`);
  } else {
    progress = {
      totalPlaces: originalDB.length,
      processedCount: 0,
      lastProcessedId: null,
      processedIds: [],
      failedIds: [],
      startedAt: new Date().toISOString(),
      lastUpdated: new Date().toISOString(),
      stats: {
        ratingsEnriched: 0,
        photosEnriched: 0,
        contactEnriched: 0,
        hoursEnriched: 0
      }
    };
  }

  // Initialize scraper
  const scraper = new GoogleScraper();
  await scraper.initialize();

  try {
    // Determine which places to process
    const alreadyProcessed = new Set(progress.processedIds);
    const toProcess = originalDB.filter(p => !alreadyProcessed.has(p.id));
    const processingList = limit ? toProcess.slice(0, limit) : toProcess;

    console.log(`\n🎯 Will process: ${processingList.length} places\n`);
    console.log('─'.repeat(70));

    for (let i = 0; i < processingList.length; i++) {
      const place = processingList[i];
      const globalIndex = progress.processedCount + i + 1;

      console.log(`\n[${globalIndex}/${originalDB.length}] ${place.name}`);
      console.log(`   📍 ${place.location.area || place.location.district || 'Unknown'}, ${place.location.island}`);
      console.log(`   🏷️  ${place.category}`);

      // Scrape Google
      console.log(`   🔍 Searching Google...`);
      const googleData = await scraper.scrapePlace(place);

      // Enrich the place
      const { enriched, changes } = enrichPlace(place, googleData);

      // Log changes
      if (changes.length > 0 && changes[0] !== 'No Google data found') {
        console.log(`   ✅ Enriched:`);
        changes.forEach(c => console.log(`      • ${c}`));
      } else {
        console.log(`   ⚠️  ${changes[0] || 'No changes'}`);
      }

      // Update enriched database
      const existingIndex = enrichedDB.findIndex(n => n.id === place.id);
      if (existingIndex >= 0) {
        enrichedDB[existingIndex] = enriched;
      } else {
        enrichedDB.push(enriched);
      }

      // Update progress
      progress.processedIds.push(place.id);
      progress.processedCount = progress.processedIds.length;
      progress.lastProcessedId = place.id;

      if (enriched.enrichment?.hasRealRating) progress.stats.ratingsEnriched++;
      if (enriched.enrichment?.hasRealPhotos) progress.stats.photosEnriched++;
      if (enriched.enrichment?.hasRealContact) progress.stats.contactEnriched++;
      if (changes.some(c => c.includes('Hours'))) progress.stats.hoursEnriched++;

      // SAVE IMMEDIATELY after each place
      saveEnrichedDatabase(enrichedDB);
      saveProgress(progress);
      console.log(`   💾 Saved (${enrichedDB.length} places in new database)`);

      // Delay before next request
      if (i < processingList.length - 1) {
        const delay = randomDelay();
        console.log(`   ⏳ Waiting ${(delay / 1000).toFixed(1)}s...`);
        await sleep(delay);
      }
    }

  } finally {
    await scraper.close();
  }

  // Final summary
  console.log('\n' + '═'.repeat(70));
  console.log('                    NURTURING COMPLETE');
  console.log('═'.repeat(70));
  console.log(`
📊 RESULTS:
   • Total processed: ${progress.processedCount}/${originalDB.length}
   • Ratings enriched: ${progress.stats.ratingsEnriched}
   • Photos enriched: ${progress.stats.photosEnriched}
   • Contact enriched: ${progress.stats.contactEnriched}
   • Hours enriched: ${progress.stats.hoursEnriched}

📁 FILES:
   • Original (SAFE): ${CONFIG.ORIGINAL_DB}
   • New enriched DB: ${CONFIG.ENRICHED_JSON}
   • TypeScript module: ${CONFIG.ENRICHED_TS}
   • Progress file: ${CONFIG.PROGRESS_FILE}

🚀 NEXT STEPS:
   1. Review: cat ${CONFIG.ENRICHED_JSON} | head -100
   2. To use in app, update imports to use enriched database
   3. Run again with --resume to continue if not complete
`);
}

main().catch(console.error);
